In [4]:
import numpy as np

In [23]:
a1 =[1,2,3,4,5,6]
a1

[1, 2, 3, 4, 5, 6]

In [24]:
a=np.array(a1)
a

array([1, 2, 3, 4, 5, 6])

In [25]:
np.reshape (a, (2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
a.reshape((2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
np.newsize(a, (2,3))

AttributeError: module 'numpy' has no attribute 'newsize'

In [28]:
np.resize(a, (2,3))

array([[1, 2, 3],
       [4, 5, 6]])

In [29]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
print(arr[:,2])

[3 8]


In [31]:
print(arr[2,:])

IndexError: index 2 is out of bounds for axis 0 with size 2

In [32]:
print(arr[0,2], " ", arr[1][2])

3   8


In [18]:
print(arr[][2])

SyntaxError: invalid syntax (<ipython-input-18-9f2e374221ef>, line 1)

In [33]:
a

array([1, 2, 3, 4, 5, 6])

In [34]:
a.sort()
a

array([1, 2, 3, 4, 5, 6])

In [35]:
print(a[1] + a[len(a)-2])
 

7


In [36]:
b1=[3, 2, 4,4,3,1]
b=np.array(b1)
b

array([3, 2, 4, 4, 3, 1])

In [37]:
np.add(a,b)

array([4, 4, 7, 8, 8, 7])

In [38]:
np.join(a,b)
 

AttributeError: module 'numpy' has no attribute 'join'

In [39]:
np.concatenate(a,b)

TypeError: only integer scalar arrays can be converted to a scalar index

In [40]:
a+b

array([4, 4, 7, 8, 8, 7])

In [42]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])) 
b = np.max(a, axis=0).sum() 
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [43]:
b

40

In [45]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10])) 
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [47]:
b2 = np.max(a, axis=0)
b2

array([ 6,  7,  8,  9, 10])

In [48]:
b=np.sum(b2)
b

40

In [50]:
x = np.array([5, 6, 7, 8, 9,10])
x

array([ 5,  6,  7,  8,  9, 10])

In [51]:
x[1:7:2]

array([ 6,  8, 10])

In [52]:
j = np.linspace(2, 4, 5) 
print( j) 
 

[2.  2.5 3.  3.5 4. ]
