### **Overview**

Dear Learner, 

Congratulations, you have studied NumPy all the way through the end of this bootcamp!!! This is the final graded hands-on exercise where you will be accomplishing the below mentioned task.

**Author:** Avantika Podar

In [1]:
import numpy as np

### Task 1:

Construct a random 3x28x28 NumPy array called *original* to represent an image and then convert this into into a 1x(3x28x28) array called *flat*. This converts it into a single row of pixels. Next, convert this to a 1D array (flatten the array using flat.flatten()). Print shape of all arrays. You may use the random function to generate the array.

In [2]:
original = np.random.random((3,28,28)) #image 
original

array([[[0.81837322, 0.54384187, 0.7341009 , ..., 0.7545819 ,
         0.47330893, 0.74431722],
        [0.73292971, 0.60134512, 0.36791162, ..., 0.25353876,
         0.30047409, 0.9193277 ],
        [0.35676303, 0.98292107, 0.38587928, ..., 0.12735501,
         0.57522874, 0.15039854],
        ...,
        [0.2830413 , 0.5014461 , 0.55462147, ..., 0.63431804,
         0.5221339 , 0.77874262],
        [0.11033531, 0.7077575 , 0.84708668, ..., 0.82458271,
         0.47672652, 0.65366174],
        [0.63480672, 0.36181605, 0.06758988, ..., 0.07963301,
         0.55015366, 0.55304828]],

       [[0.43165204, 0.38039736, 0.0647872 , ..., 0.0858266 ,
         0.41326452, 0.47304662],
        [0.58986091, 0.73779372, 0.99892091, ..., 0.3725731 ,
         0.70884077, 0.53774407],
        [0.9728947 , 0.14622557, 0.98894491, ..., 0.37778044,
         0.13439368, 0.84620655],
        ...,
        [0.31444765, 0.13430717, 0.75299012, ..., 0.62996158,
         0.19931174, 0.06769652],
        [0.9

In [3]:
print(original.shape)

(3, 28, 28)


In [4]:
flat = np.array([original])
flat

array([[[[0.81837322, 0.54384187, 0.7341009 , ..., 0.7545819 ,
          0.47330893, 0.74431722],
         [0.73292971, 0.60134512, 0.36791162, ..., 0.25353876,
          0.30047409, 0.9193277 ],
         [0.35676303, 0.98292107, 0.38587928, ..., 0.12735501,
          0.57522874, 0.15039854],
         ...,
         [0.2830413 , 0.5014461 , 0.55462147, ..., 0.63431804,
          0.5221339 , 0.77874262],
         [0.11033531, 0.7077575 , 0.84708668, ..., 0.82458271,
          0.47672652, 0.65366174],
         [0.63480672, 0.36181605, 0.06758988, ..., 0.07963301,
          0.55015366, 0.55304828]],

        [[0.43165204, 0.38039736, 0.0647872 , ..., 0.0858266 ,
          0.41326452, 0.47304662],
         [0.58986091, 0.73779372, 0.99892091, ..., 0.3725731 ,
          0.70884077, 0.53774407],
         [0.9728947 , 0.14622557, 0.98894491, ..., 0.37778044,
          0.13439368, 0.84620655],
         ...,
         [0.31444765, 0.13430717, 0.75299012, ..., 0.62996158,
          0.19931174, 0.0

In [5]:
print(flat.shape)

(1, 3, 28, 28)


In [6]:
arr_1D=flat.flatten()
arr_1D

array([0.81837322, 0.54384187, 0.7341009 , ..., 0.4386843 , 0.38076121,
       0.50840589])

In [7]:
print(arr_1D.shape)

(2352,)


### Task 2: Print out the following: 
  * dimension of the arrays.
  * memory address of the arrays (pointer).
  * shape of the arrays.
  * data types of the arrays. 




**dimension of the arrays**

In [8]:
original.ndim

3

In [9]:
flat.ndim

4

In [10]:
arr_1D.ndim

1

**memory address of the arrays (pointer)**

In [11]:
original.data

In [12]:
flat.data

In [13]:
arr_1D.data

**shape of the arrays**

In [14]:
original.shape

(3, 28, 28)

In [15]:
flat.shape

(1, 3, 28, 28)

In [16]:
arr_1D.shape

(2352,)

**data types of the arrays**

In [17]:
original.dtype

dtype('float64')

In [18]:
flat.dtype

dtype('float64')

In [19]:
arr_1D.dtype

dtype('float64')

### Task 3
Construct a new array which is a negative of the *original* array, i.e, all elements are negative of those in the *original* array. Print the new array. Add the original and new arrays. Print the result. 

In [20]:
neg_original=np.negative(original)
neg_original

array([[[-0.81837322, -0.54384187, -0.7341009 , ..., -0.7545819 ,
         -0.47330893, -0.74431722],
        [-0.73292971, -0.60134512, -0.36791162, ..., -0.25353876,
         -0.30047409, -0.9193277 ],
        [-0.35676303, -0.98292107, -0.38587928, ..., -0.12735501,
         -0.57522874, -0.15039854],
        ...,
        [-0.2830413 , -0.5014461 , -0.55462147, ..., -0.63431804,
         -0.5221339 , -0.77874262],
        [-0.11033531, -0.7077575 , -0.84708668, ..., -0.82458271,
         -0.47672652, -0.65366174],
        [-0.63480672, -0.36181605, -0.06758988, ..., -0.07963301,
         -0.55015366, -0.55304828]],

       [[-0.43165204, -0.38039736, -0.0647872 , ..., -0.0858266 ,
         -0.41326452, -0.47304662],
        [-0.58986091, -0.73779372, -0.99892091, ..., -0.3725731 ,
         -0.70884077, -0.53774407],
        [-0.9728947 , -0.14622557, -0.98894491, ..., -0.37778044,
         -0.13439368, -0.84620655],
        ...,
        [-0.31444765, -0.13430717, -0.75299012, ..., -

In [21]:
result = original + neg_original
result

array([[[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]],

       [[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]]])

### Task 4

A 3x28x28 basically means 28x28 matrices repeated three times. How would you access the first 10 elements of the 2nd row of the second 28x28 matrix? Consider the original array for this. Print the elements.

In [29]:
arr1 = original [1]
arr1

array([[0.43165204, 0.38039736, 0.0647872 , 0.28002165, 0.86051345,
        0.13914312, 0.54713684, 0.55868731, 0.6525787 , 0.11696961,
        0.26706249, 0.91840788, 0.94940258, 0.35164829, 0.39414839,
        0.13501163, 0.17026394, 0.86965051, 0.14286338, 0.76481732,
        0.56290993, 0.97938928, 0.20155555, 0.53617989, 0.94111084,
        0.0858266 , 0.41326452, 0.47304662],
       [0.58986091, 0.73779372, 0.99892091, 0.19195858, 0.95473629,
        0.78077608, 0.05233412, 0.52287892, 0.98339324, 0.9892337 ,
        0.62895317, 0.96625032, 0.90541316, 0.87793387, 0.27546698,
        0.80795454, 0.72169251, 0.80048853, 0.16297707, 0.27767643,
        0.6492483 , 0.56451182, 0.50624967, 0.78097937, 0.35393838,
        0.3725731 , 0.70884077, 0.53774407],
       [0.9728947 , 0.14622557, 0.98894491, 0.79354114, 0.11342476,
        0.14868459, 0.97293171, 0.81230499, 0.6199093 , 0.28077143,
        0.45938598, 0.34045696, 0.36010899, 0.80350783, 0.0857723 ,
        0.42166561, 0.6790

In [31]:
arr2 = arr1[1]
arr2

array([0.58986091, 0.73779372, 0.99892091, 0.19195858, 0.95473629,
       0.78077608, 0.05233412, 0.52287892, 0.98339324, 0.9892337 ,
       0.62895317, 0.96625032, 0.90541316, 0.87793387, 0.27546698,
       0.80795454, 0.72169251, 0.80048853, 0.16297707, 0.27767643,
       0.6492483 , 0.56451182, 0.50624967, 0.78097937, 0.35393838,
       0.3725731 , 0.70884077, 0.53774407])

In [34]:
arr2 [0:10]

array([0.58986091, 0.73779372, 0.99892091, 0.19195858, 0.95473629,
       0.78077608, 0.05233412, 0.52287892, 0.98339324, 0.9892337 ])

### Task 5 
A 3x28x28 image means 3 channels of Red, Green, or Blue (Popularly known as RGB image). Each color channel has a height and width, which is 28X28 in this case. The entire picture can represented through this method. Print the shape of the Blue pixel matrix and its first 3 rows.

In [35]:
blue = original [2]
blue

array([[0.89602998, 0.12531591, 0.40681879, 0.55823939, 0.28575186,
        0.96389061, 0.09436157, 0.50539434, 0.82504383, 0.81673973,
        0.12246983, 0.08531778, 0.41609575, 0.2067733 , 0.7160015 ,
        0.4053551 , 0.85290267, 0.3223274 , 0.15829599, 0.68576512,
        0.89493747, 0.88763217, 0.32326431, 0.0788654 , 0.13311565,
        0.33010784, 0.72834318, 0.02873885],
       [0.84723818, 0.15565463, 0.75393308, 0.08790336, 0.4392536 ,
        0.41643754, 0.42724752, 0.17511721, 0.64843226, 0.14405522,
        0.48770137, 0.74568021, 0.88381427, 0.16999844, 0.09645809,
        0.0199189 , 0.33667914, 0.59442103, 0.04873386, 0.49512559,
        0.81615121, 0.94994882, 0.52243711, 0.53163733, 0.27641548,
        0.92568775, 0.21149595, 0.51220958],
       [0.5853237 , 0.77969678, 0.70141802, 0.56599123, 0.15323334,
        0.35278262, 0.54800157, 0.08943976, 0.72897611, 0.48972603,
        0.30416492, 0.28940057, 0.61665285, 0.13298267, 0.85312564,
        0.58319267, 0.8217

In [36]:
blue.shape

(28, 28)

In [42]:
blue_3rows = blue [0:3]
blue_3rows

array([[0.89602998, 0.12531591, 0.40681879, 0.55823939, 0.28575186,
        0.96389061, 0.09436157, 0.50539434, 0.82504383, 0.81673973,
        0.12246983, 0.08531778, 0.41609575, 0.2067733 , 0.7160015 ,
        0.4053551 , 0.85290267, 0.3223274 , 0.15829599, 0.68576512,
        0.89493747, 0.88763217, 0.32326431, 0.0788654 , 0.13311565,
        0.33010784, 0.72834318, 0.02873885],
       [0.84723818, 0.15565463, 0.75393308, 0.08790336, 0.4392536 ,
        0.41643754, 0.42724752, 0.17511721, 0.64843226, 0.14405522,
        0.48770137, 0.74568021, 0.88381427, 0.16999844, 0.09645809,
        0.0199189 , 0.33667914, 0.59442103, 0.04873386, 0.49512559,
        0.81615121, 0.94994882, 0.52243711, 0.53163733, 0.27641548,
        0.92568775, 0.21149595, 0.51220958],
       [0.5853237 , 0.77969678, 0.70141802, 0.56599123, 0.15323334,
        0.35278262, 0.54800157, 0.08943976, 0.72897611, 0.48972603,
        0.30416492, 0.28940057, 0.61665285, 0.13298267, 0.85312564,
        0.58319267, 0.8217

### Task 6 
Create a 1 dimensional numpy array of the first 50 even numbers. Convert this to a 10x5 numpy array and print its transpose. 

In [49]:
arr_even = np.arange(2,102,2)
arr_even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [50]:
arr_even.shape

(50,)

In [51]:
arr_10x5 = np.reshape(arr_even,(10,5))
arr_10x5

array([[  2,   4,   6,   8,  10],
       [ 12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30],
       [ 32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50],
       [ 52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70],
       [ 72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90],
       [ 92,  94,  96,  98, 100]])

In [52]:
arr_10x5_transpose = np.transpose(arr_10x5)
arr_10x5_transpose

array([[  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

### Task 7 
Consider the 10x5 array created in Task 6. Find the mean of each row and column. You may use in built functions or write your own code.

In [56]:
column_means = arr_10x5.mean(axis=0)
column_means

array([47., 49., 51., 53., 55.])

In [57]:
row_means = arr_10x5.mean(axis=1)
row_means

array([ 6., 16., 26., 36., 46., 56., 66., 76., 86., 96.])

### Task 8
Can we create a 3x3 array of the first 50 even numbers? Why or why not? What are other values of m and n for which mxn dimension is allowed for 50 elements?

In [58]:
arr_3x3 = np.reshape(arr_even,(3,3))
arr_3x3

ValueError: cannot reshape array of size 50 into shape (3,3)

No, we cannot create a 3x3 array of the first 50 even numbers because it has not the same total number of elements of the first 50 even numbers array

other values of m and n for which mxn dimension is allowed for 50 elements:

- (5,10) 
- (10,5) 
- (1,50) 
- (50,1) 
- (2,25)  
- (25,2)